---
- hosts: localhost
  gather_facts: False
  tasks:
    - shell: 'date +%Y%m%d%H%M%S'
      register: current_run_timestamp
      tags: [always]

- hosts: cassandra_node
  gather_facts: True
  become: true
  roles:
    - { role: instana-cassandra }

- hosts: clickhouse_node
  gather_facts: True
  become: true
  roles:
    - { role: instana-clickhouse }

- hosts: cockroachdb_node
  gather_facts: True
  roles:
    - { role: instana-cockroachdb }

- hosts: elasticsearch_node
  gather_facts: True
  become: true
  roles:
    - { role: instana-elasticsearch }

- hosts: kafka_node
  become: true
  gather_facts: True
  roles:
    - { role: instana-kafka }

- hosts: zookeeper_node
  gather_facts: True
  become: true
  roles:
    - { role: instana-zookeeper }

- hosts: dbsvrs
  gather_facts: False
  tasks:
    - name: Show the status for all datastores
      import_role:
        name: dbsvrs-common
        tasks_from: status_report
      tags: [always]