---

- name: Importing GPG key for instana-product
  rpm_key:
    state: present
    key: https://self-hosted.instana.io/signing_key.gpg
  become: true
  # environment: "{{ proxy_env }}"
  register: import_instana_gpg

- name: Enable Instana-Product repo for RedHat/CentOS
  yum_repository:
    file: Instana-Product
    name: instana-product
    description: Instana Product Installation Package Repo
    baseurl: https://self-hosted.instana.io/rpm/release/product/rpm/generic/x86_64/Packages
    enabled: yes
    gpgcheck: yes
    repo_gpgcheck: yes
    gpgkey: https://self-hosted.instana.io/signing_key.gpg
    priority: "5"
    sslverify: yes
    skip_if_unavailable: yes
  become: true

# limitation: Instana Repository metadata signatures are checked by yum using a separate set of keys
# which it stores under /var/cache/yum/repos/. https://github.com/ansible/ansible/issues/20711
- name: Make cache to FORCE gpg key imported.
  command: "yum makecache -y fast"
