---

- name: Remove clickhouse config,data and logs
  file:
    dest: "{{ item }}"
    state: absent
  loop:
    - "{{ clickhouse.log_dir }}"
    - "{{ clickhouse.data_dir }}"
    - "/etc/clickhouse-client/"
    - "/etc/clickhouse-server/"
  become: true
  when: clickhouse_remove_full

- include_tasks: "remove/{{ ansible_pkg_mgr }}.yml"
