---
- name: check cluster master
  debug:
    msg: "{{ cockroachdb.cluster_master }}"

- set_fact:
    ck_cluster_master: "{{ cockroachdb.cluster_master }}"

- name: start cockrachdb service
  systemd:
    name: cockroachdb
    enabled: yes
    state: started
    daemon_reload: yes

- name: Wait for port {{ cockroachdb.configuration.port }} to become open on the host, don't start checking for 10 seconds
  wait_for:
    port: "{{ cockroachdb.configuration.port }}"
    host: "{{ ansible_default_ipv4.address }}"
    delay: 3
    timeout: 15

- name: perform cockroachdb cluster init
  shell: "{{ cockroachdb.install_dir }}/{{ cockroachdb.version }}/cockroach init --insecure --host={{ ansible_default_ipv4.address }}:{{ cockroachdb.configuration.port }}"
  become_user: cockroachdb
  when: inventory_hostname == ck_cluster_master
  ignore_errors: True

- name: check status
  shell: "{{ cockroachdb.install_dir }}/{{ cockroachdb.version }}/cockroach node status --host {{ ansible_default_ipv4.address }} --insecure"
  register: cockroachdb_node_status
  become_user: cockroachdb

- name: check status
  debug: var=cockroachdb_node_status.stdout_lines
  become_user: cockroachdb
